# Generated by Django 5.0.4 on 2024-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porpertybook',
            name='children',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
