# Generated by Django 5.0.4 on 2024-04-30 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_porpertybook_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='porpertybook',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
